### ISSUE TITLE
Missing spaces in GSC code

### ISSUE THREAD

**Issue by itsEmDoubleyou** [XLabsProject/iw4x-map-porting-utility#3]
When porting a map some GSC code is missing a space, sometimes.

For reference Map Rasalem (CoD4) https://www.customapscod.com/dld.php?id=MTIyMA==
![image](https://github.com/iw4x/iw4x-map-porting-utility/assets/33820489/f028b55b-2273-47b2-b14f-09d6379f40c2)
![immage](https://github.com/iw4x/iw4x-map-porting-utility/assets/33820489/0a4053fd-aea3-47b4-8e3f-6bfc4949536e)

**Comment by louvenarde** [comment]
Sorry I didn't see this earlier- this is a bug for the IW3x repo! 
If it is still a bug that exists, please open an issue there :)
